language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bradsorour/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run bradsorour/react-test npm test -- --coverage
  - docker run -e CI=true bradsorour/react-test npm test

after_success:
  - docker build -t bradsorour/multi-client ./client
  - docker build -t bradsorour/multi-nginx ./nginx 
  - docker build -t bradsorour/multi-server ./multi-server
  - docker build -t bradsorour/multi-worker ./worker
  # Log into to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push the to docker hub
  - docker push bradsorour/multi-client
  - docker push bradsorour/multi-nginx
  - docker push bradsorour/multi-server
  - docker push bradsorour/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-745356072809
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"


