sudo: required
services:
  - docker

before_install:
  - docker build -t bradsorour/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bradsorour/react-test npm test -- --coverage

after_success:
  - docker build -t bradsorour/multi-client ./client
  - docker build -t bradsorour/multi-nginx ./nginx 
  - docker build -t bradsorour/multi-server ./multi-server
  - docker build -t bradsorour/multi-worker ./worker
  # Log into to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push the to docker hub
  - docker push bradsorour/multi-client
  - docker push bradsorour/multi-nginx
  - docker push bradsorour/multi-server
  - docker push bradsorour/multi-worker


